---
title: "Torrential Twitter? Investigating the Severity of Harassment when Canadian Female Politicians Tweet about Climate Change"
author: "Inessa De Angelis"
thanks: "Code and other information available at: https://github.com/InessaDeAngelis/Torrential_Twitter_Trial "
date: "today"
date-format: "long"
abstract: "This paper analyzes Tweets which specifically discuss climate change from former MP Catherine McKenna, MP Elizabeth May, and MP Laurel Collins to investigate the severity of harassment on a seven-point scale and type of accounts behind the Tweets."
format: pdf
toc: true
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

#### Workspace set-up ####

## Load packages ##
library(tidyverse)
library(knitr)
library(kableExtra)
library(here)
library(ggplot2)

# Read in the cleaned McKenna data # 
cleaned_mckenna_data <- read.csv(here::here("~/Desktop/Final Paper/Outputs/Data/finalized_mckenna_data.csv"))
show_col_types = FALSE

# Read in the cleaned May data #
cleaned_may_data <- read.csv(here::here("~/Desktop/Final Paper/Outputs/Data/finalized_may_data.csv"))
show_col_types = FALSE

# Read in the cleaned Collins data #
cleaned_collins_data <- read.csv(here::here("~/Desktop/Final Paper/Outputs/Data/finalized_collins_data.csv"))
show_col_types = FALSE

# Create specific data sets #

```

# Introduction

## Theoretical Framework
This study is conducted under the theory of deliberative democracy which emphasizes the importance of having open, respectful, and diverse discourse for a healthy democracy [@pmc2019; @trifiro]. Democratic legitimacy is established by allowing the public to collectively have the opportunity “... to participate in consequential deliberation about the content of decisions” [@mckaytenove, p. 704]. Masullo Chen categorizes the characteristics of a deliberative debate by stating that there must be “… more than one side of an issue to consider [and that] the stakes also must be high” [@masullochen, pp. 83-84]. The harassment of female politicians who communicate about climate change, one of the most crucial areas of policymaking, challenges the core values of Canada’s deliberative democracy by trying to minimize the diverse range of opinions and politicize the subject matter, therefore risking the future of public discourse online and offline.

Results from the analyzed Tweets from the three female politicians will then be compared to see if the level of discourse about climate change on Twitter matches the characteristics of what is considered healthy discourse under the theory of deliberative democracy. 

# Data

## Data Coding

## Data Limitations

## Data Cleaning
Data was collected via Twitter API using Python (see datasheet in [Appendix] for more information) and cleaned, tested, modeled, and analyzed using the statistical programming software R [@r], using functions from `tidyverse` [@rTidyverse], `ggplot2` [@rGgplot2], `janitor` [@rJanitor], `KableExtra` [@rKableExtra], `knitr` [@rknitr], `here` [@rHere], `arrow` [@arrow], `validate` [@validate], and `testthat` [@testthat]. 

After retrieving the data sets from my archived files, I performed the first round of data cleaning based on the design of my trial study. I removed the columns which presented information not required for this study and using the `filter` function, I filtered all Tweets by the key word "climate", and then took a sample using the `slice_sample` function of 500 Tweets from both MP McKenna and MP May's data sets. Only 13 Tweets from MP Collins matched the criteria, so there was no need to take a sample. 

### Raw Data 
In preparation to code my Tweets, 

I renamed columns and capitalized the first letter of every word using Twitter Developer's guidelines and my Codebook [@Twittermedia]. I renamed `text` to `Text`, `user_name` to `Name`, `user_sname` to `Username`, `user_description` to `Bio`, `user_location` to `Location`, `followers` to `Followers`, `friends` to `Following`, and `tweet_URL` to `URL`. 

I then tested the raw data using the `testthat` [@testthat] package to ensure the data set was ready to be manually coded.

### Coded Data 
After coding the 1,013 Tweets manually using my Google form, I then visually checked for missing data, such as Tweet URLs, severity of harassment, and type of account and went back and added in the few that I missed coding the first time. A number of Twitter accounts opted not have bios (listed as NA in the data sets), which is missing data that was anticipated within the data sets. After my data set passed this initial, informal test, I proceeded to clean it a second time. 

For my `severity of harassment` data, I updated value 1 to "Positive", 2 to "Neutral", 3 to "Questioning authority", 4 to "Name-calling/Gender insults", 5 to "Vicious language", 6 to "Credible threats", and 7 to "Hate speech" based on my Codebook. 

For my `type of account` data, I changed value 1 to "Personal", 2 to "Professional", 3 to "Bots", 4 to "Spammers", 5 to "Anonymous", and 6 to "Suspended/deleted" based on my Codebook. 

I tested the cleaned data using the `validate` [@validate] package, primarily validating variable types and ensuring all Tweets were coded (500 for both MP McKenna and MP May and 13 for MP Collins). 

# Results

## Severity of Harassment

## Type of Account

## Catherine McKenna

## Elizabeth May

## Laurel Collins

# Discussion

## Deliberative Democracy
Referencing previous discussions of the characteristics of what constitutes a healthy deliberative democracy, findings from this trial study will be compared and contrasted to evaluate the extent at which the discourse is healthy for Canadian democracy. 

## Limitations

## Future Research
Given the changes to Twitter's affordances and the increasingly polarized political climate in Canada following the Covid-19 pandemic, there are multiple aspects of this trial study that will differ in the full-scale version of this study. 

# Conclusion

# Appendix {.unnumbered}

This datasheet provides background on who originally collected the raw Twitter data used in this trial study, how it has been previously used, and aims to minimize some of the unknowns. The questions below are amended from the ones outlined in @gebru2021datasheets. 

## Motivation
1. *For what purpose was the dataset created? Was there a specific task in mind? Was there a specific gap that needed to be filled? Please provide a description.*

    - This dataset was created for a group project under the theme “who follows and mentions who during elections” for        CMN 4160 - Digital Social Research taught by Professor Elizabeth Dubois at the University of Ottawa. 

    - Inessa De Angelis was the group member who led research project design and pitched the idea of selecting former       MP Catherine McKenna, MP Elizabeth May, and MP Laurel Collins because of their engagement in climate change           policy advocacy. 

    - Because of her previous work with Catherine McKenna during the 2019 Federal Election Campaign, Inessa noticed         the connection between climate change denial, misogyny, and online harassment. After reviewing relevant               literature from both Canada and other countries, Inessa noticed a large gap and wanted to help fill the gap           through this project and her continued research at the Faculty of Information at the University of Toronto. 

    - The dataset specifically collected mentions of the three female politicians, not simply replies, which differs        from how Inessa will approach the full-scale version of this project. Instead of quantitative content                 analysis, the group performed social network analysis using Gephi on the datasets. 

2. *Who created the dataset (for example, which team, research group) and on behalf of which entity (for example, company, institution, organization)?*

    - Inessa defined the parameters on behalf of her group of what data they wanted collected and Trevor Deley, PhD         Candidate in E-Business (supervised by Professor Dubois) collected the data. Both were students at the                University of Ottawa. 

3. *Who funded the creation of the dataset? If there is an associated grant, please provide the name of the grantor and the grant name and number.*

    - Trevor's financial situation during the creation of this dataset is unknown.

    - Inessa’s tuition was partially covered by a University of Ottawa Dean’s Honour List Merit Scholarship, but there      was no direct grant associated with this project.

## Composition

1. *What do the instances that comprise the dataset represent (for example, documents, photos, people, countries)?* 
    
    - Each row of the dataset is an individual. 

2. *Is the dataset self-contained, or does it link to or otherwise rely on external resources?*
    
    - It is self-contained. 
    

3. *Are there any errors, sources of noise, or redundancies in the dataset?*
 
     -  It has been over four years since these Tweets were initally sent and over two years since these Tweets were          collected for the dataset, so there is potential inaccuracies in reporting which accounts are still on the            platform and which have been suspended/deleted.
     - Some users do not have bios or locations indicated (listed as NA), which may impact how coders categorized             "type of account".

## Collection Process

1. *What mechanisms or procedures were used to collect the data (for example, hardware apparatuses or sensors, manual human curation, software programs, software APIs)? How were these mechanisms or procedures validated?*

    -  Trevor collected these Tweets using a custom Python script to access Twitter’s API. The Tweets were also run         through Perspective API’s sentiment detection software to check for toxicity and assign a score,                      although Inessa removed these scores during the initial cleaning process for this paper. 
    
2. *Who was involved in the data collection process (for example, students, crowdworkers, contractors) and how were they compensated (for example, how much were crowdworkers paid)?*

    - Trevor Deley (compensation unknown).
    
    - Professor Elizabeth Dubois (Associate Professor salary from the University of Ottawa, but not directly for this       project).
    
    - Inessa De Angelis (no compensation, paid tuition to the University of Ottawa to take CMN 4160).

3. *Were any ethical review processes conducted (for example, by an institutional review board)?*

    - No.

4. *Were the individuals in question notified about the data collection?*

    - No.
    
5. *Did the individuals in question consent to the collection and use of their data?*

    - No.

## Cleaning/Labelling 

1. *Was any preprocessing/cleaning/labeling of the data done?*

    - It is unknown whether Trevor conducted any cleaning of the raw datasets with Python, beyond obtaining toxicity        scores via Perspective API. 
    
    - For this trial study, Inessa used R to clean and simplify column names, remove additional variables, and filter       out Tweets which did not contain the word `climate`.
    
2. *Was the "raw" data saved in addition to the preprocessed/cleaned/labeled data (for example, to support unanticipated future uses)?*

    - Yes. Inessa has the original raw data sets saved in her personal Google Drive and on the desktop of her personal       Mac. 
    
3. *Is the software that was used to preprocess/clean/label the data available? If so, please provide a link or other access point.*

    - Trevor used Python and Perspective API by Jigsaw. Perspective API is currently free to use but requires                registration.
    
    - Inessa uses R. 
    
    
## Uses

1. *Has the dataset been used for any tasks already? If so, please provide a description*

    - Yes. This dataset was used for the aforementioned CMN 4160 class project. 
    
    - We used Gephi to conduct social network analysis to see which communities formed around the Tweets and Twitter        accounts of former MP Catherine McKenna, MP Elizabeth May, and MP Laurel Collins. We found that McKenna had 26        communities, May had 131 communities, and Collins had 18. We also found that harssment was sent by users with         personal accounts and was most likely to show up in the same community as the three female politicans. These          findings were written up in a professional-style guide, aimed at women running for office. This project report        was used by Professor Dubois as an example for future students in her class, but not publicly distributed beyond      the class’ Brightspace page. 

2. *Is there a repository that links to any or all papers or systems that use the dataset?*
  
    - No.
    
## Distribution

1. *Will the dataset be distributed to third parties outside of the entity (for example, company, institution, organization) on behalf of which the dataset was created?* 

    - No. Due to Twitter’s policies about sharing data, this dataset is not publicly available but can be obtained by       contacting Inessa De Angelis (inessa.deangelis@mail.utoronto.ca). Twitter’s policies outline that datasets are not to be uploaded to GitHub or similar sites/repositories without removing all identifying information and only including the Tweet ID or User ID. 


# References